/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author ayyub
 */
public class MiPrimeraVentana extends javax.swing.JFrame {

    /**
     * Creates new form MiPrimeraVentana
     */
    public MiPrimeraVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoInformativo = new javax.swing.JLabel();
        Saludar = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Saludo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        textoInformativo.setBackground(new java.awt.Color(0, 0, 0));
        textoInformativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoInformativo.setForeground(new java.awt.Color(0, 0, 255));
        textoInformativo.setText("Introduce aqui tu nombre:");
        textoInformativo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                textoInformativoMouseMoved(evt);
            }
        });
        textoInformativo.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                textoInformativoMouseWheelMoved(evt);
            }
        });
        textoInformativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoInformativoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoInformativoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textoInformativoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textoInformativoMouseReleased(evt);
            }
        });

        Saludar.setText("Saludar");
        Saludar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaludarMouseClicked(evt);
            }
        });
        Saludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaludarActionPerformed(evt);
            }
        });

        Salida.setText("Salir");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreFocusLost(evt);
            }
        });
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombreKeyReleased(evt);
            }
        });

        Saludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaludoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Saludar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Saludo)
                    .addComponent(Nombre))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textoInformativo)
                .addGap(27, 27, 27)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Saludar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaludarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaludarActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalidaActionPerformed

    private void SaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaludoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaludoActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
        System.out.println("probando");
    }//GEN-LAST:event_NombreActionPerformed

    private void SaludarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaludarMouseClicked
        // TODO add your handling code here:
        System.out.println("Se ha hecho click en la etiqueta");
    }//GEN-LAST:event_SaludarMouseClicked

    private void textoInformativoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoInformativoMouseEntered
        // TODO add your handling code here:
        System.out.println("entro");
    }//GEN-LAST:event_textoInformativoMouseEntered

    private void textoInformativoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoInformativoMouseExited
        // TODO add your handling code here:
        System.out.println("salgo");
    }//GEN-LAST:event_textoInformativoMouseExited

    private void textoInformativoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoInformativoMouseMoved
        // TODO add your handling code here:
        System.out.println("moviendo");
    }//GEN-LAST:event_textoInformativoMouseMoved

    private void textoInformativoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoInformativoMousePressed
        // TODO add your handling code here:
        System.out.println("bajando..");
    }//GEN-LAST:event_textoInformativoMousePressed

    private void textoInformativoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoInformativoMouseReleased
        // TODO add your handling code here:
        System.out.println("subiendo");
    }//GEN-LAST:event_textoInformativoMouseReleased

    private void textoInformativoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_textoInformativoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textoInformativoMouseWheelMoved

    private void NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusLost
        // TODO add your handling code here:
        //System.out.println("pierde el foco");
    }//GEN-LAST:event_NombreFocusLost

    private void NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusGained
        // TODO add your handling code here:
       // System.out.println("gana el foco");
    }//GEN-LAST:event_NombreFocusGained

    private void NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyPressed
        // TODO add your handling code here:
       // System.out.println("Tecla hacia abajo");
    }//GEN-LAST:event_NombreKeyPressed

    private void NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyReleased
        // TODO add your handling code here:
        //System.out.println("Tecla hacia arriba");
    }//GEN-LAST:event_NombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPrimeraVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Salida;
    private javax.swing.JButton Saludar;
    private javax.swing.JTextField Saludo;
    private javax.swing.JLabel textoInformativo;
    // End of variables declaration//GEN-END:variables
}
